/** Target places the player must find. Each entry: name, type, lat, lon. */
const RAW_PLACES = [
  // ── Africa ───────────────────────────────────────────────────────────────
  { name: 'Algeria',                    type: 'country', lat:  28.03, lon:   1.66 },
  { name: 'Angola',                     type: 'country', lat: -11.20, lon:  17.87 },
  { name: 'Benin',                      type: 'country', lat:   9.31, lon:   2.32 },
  { name: 'Botswana',                   type: 'country', lat: -22.33, lon:  24.68 },
  { name: 'Burkina Faso',               type: 'country', lat:  12.36, lon:  -1.53 },
  { name: 'Burundi',                    type: 'country', lat:  -3.37, lon:  29.92 },
  { name: 'Cabo Verde',                 type: 'country', lat:  16.54, lon: -23.04 },
  { name: 'Cameroon',                   type: 'country', lat:   3.85, lon:  11.50 },
  { name: 'Central African Republic',   type: 'country', lat:   6.61, lon:  20.94 },
  { name: 'Chad',                       type: 'country', lat:  15.45, lon:  18.73 },
  { name: 'Comoros',                    type: 'country', lat: -11.88, lon:  43.87 },
  { name: 'Congo',                      type: 'country', lat:  -0.23, lon:  15.83 },
  { name: 'DR Congo',                   type: 'country', lat:  -4.04, lon:  21.76 },
  { name: 'Djibouti',                   type: 'country', lat:  11.83, lon:  42.59 },
  { name: 'Egypt',                      type: 'country', lat:  26.82, lon:  30.80 },
  { name: 'Equatorial Guinea',          type: 'country', lat:   1.65, lon:  10.27 },
  { name: 'Eritrea',                    type: 'country', lat:  15.18, lon:  39.78 },
  { name: 'Eswatini',                   type: 'country', lat: -26.52, lon:  31.47 },
  { name: 'Ethiopia',                   type: 'country', lat:   9.15, lon:  40.49 },
  { name: 'Gabon',                      type: 'country', lat:  -0.80, lon:  11.61 },
  { name: 'Gambia',                     type: 'country', lat:  13.44, lon: -15.31 },
  { name: 'Ghana',                      type: 'country', lat:   7.95, lon:  -1.02 },
  { name: 'Guinea',                     type: 'country', lat:   9.95, lon: -11.24 },
  { name: 'Guinea-Bissau',              type: 'country', lat:  11.80, lon: -15.18 },
  { name: 'Ivory Coast',                type: 'country', lat:   7.54, lon:  -5.55 },
  { name: 'Kenya',                      type: 'country', lat:  -0.02, lon:  37.91 },
  { name: 'Lesotho',                    type: 'country', lat: -29.61, lon:  28.23 },
  { name: 'Liberia',                    type: 'country', lat:   6.43, lon:  -9.43 },
  { name: 'Libya',                      type: 'country', lat:  26.34, lon:  17.23 },
  { name: 'Madagascar',                 type: 'country', lat: -18.77, lon:  46.87 },
  { name: 'Malawi',                     type: 'country', lat: -13.25, lon:  34.30 },
  { name: 'Mali',                       type: 'country', lat:  17.57, lon:  -3.99 },
  { name: 'Mauritania',                 type: 'country', lat:  21.01, lon: -10.94 },
  { name: 'Mauritius',                  type: 'country', lat: -20.35, lon:  57.55 },
  { name: 'Morocco',                    type: 'country', lat:  31.79, lon:  -7.09 },
  { name: 'Mozambique',                 type: 'country', lat: -18.67, lon:  35.53 },
  { name: 'Namibia',                    type: 'country', lat: -22.96, lon:  18.49 },
  { name: 'Niger',                      type: 'country', lat:  17.61, lon:   8.08 },
  { name: 'Nigeria',                    type: 'country', lat:   9.08, lon:   8.68 },
  { name: 'Rwanda',                     type: 'country', lat:  -1.94, lon:  29.87 },
  { name: 'São Tomé and Príncipe',      type: 'country', lat:   0.19, lon:   6.61 },
  { name: 'Senegal',                    type: 'country', lat:  14.50, lon: -14.45 },
  { name: 'Seychelles',                 type: 'country', lat:  -4.68, lon:  55.49 },
  { name: 'Sierra Leone',               type: 'country', lat:   8.46, lon: -11.78 },
  { name: 'Somalia',                    type: 'country', lat:   5.15, lon:  46.20 },
  { name: 'South Africa',               type: 'country', lat: -30.56, lon:  22.94 },
  { name: 'South Sudan',                type: 'country', lat:   7.86, lon:  29.69 },
  { name: 'Sudan',                      type: 'country', lat:  12.86, lon:  30.22 },
  { name: 'Tanzania',                   type: 'country', lat:  -6.37, lon:  34.89 },
  { name: 'Togo',                       type: 'country', lat:   8.62, lon:   0.82 },
  { name: 'Tunisia',                    type: 'country', lat:  33.89, lon:   9.54 },
  { name: 'Uganda',                     type: 'country', lat:   1.37, lon:  32.29 },
  { name: 'Zambia',                     type: 'country', lat: -13.13, lon:  27.85 },
  { name: 'Zimbabwe',                   type: 'country', lat: -19.02, lon:  29.15 },

  // ── Asia ─────────────────────────────────────────────────────────────────
  { name: 'Afghanistan',                type: 'country', lat:  33.94, lon:  67.71 },
  { name: 'Armenia',                    type: 'country', lat:  40.07, lon:  45.04 },
  { name: 'Azerbaijan',                 type: 'country', lat:  40.14, lon:  47.58 },
  { name: 'Bahrain',                    type: 'country', lat:  26.07, lon:  50.55 },
  { name: 'Bangladesh',                 type: 'country', lat:  23.68, lon:  90.36 },
  { name: 'Bhutan',                     type: 'country', lat:  27.51, lon:  90.43 },
  { name: 'Brunei',                     type: 'country', lat:   4.54, lon: 114.73 },
  { name: 'Cambodia',                   type: 'country', lat:  12.57, lon: 104.99 },
  { name: 'China',                      type: 'country', lat:  35.86, lon: 104.20 },
  { name: 'Cyprus',                     type: 'country', lat:  35.13, lon:  33.43 },
  { name: 'Georgia',                    type: 'country', lat:  42.32, lon:  43.36 },
  { name: 'India',                      type: 'country', lat:  20.59, lon:  78.96 },
  { name: 'Indonesia',                  type: 'country', lat:  -0.79, lon: 113.92 },
  { name: 'Iran',                       type: 'country', lat:  32.43, lon:  53.69 },
  { name: 'Iraq',                       type: 'country', lat:  33.22, lon:  43.68 },
  { name: 'Israel',                     type: 'country', lat:  31.05, lon:  34.85 },
  { name: 'Japan',                      type: 'country', lat:  36.20, lon: 138.25 },
  { name: 'Jordan',                     type: 'country', lat:  30.59, lon:  36.24 },
  { name: 'Kazakhstan',                 type: 'country', lat:  48.02, lon:  66.92 },
  { name: 'Kuwait',                     type: 'country', lat:  29.31, lon:  47.48 },
  { name: 'Kyrgyzstan',                 type: 'country', lat:  41.20, lon:  74.77 },
  { name: 'Laos',                       type: 'country', lat:  19.86, lon: 102.50 },
  { name: 'Lebanon',                    type: 'country', lat:  33.85, lon:  35.86 },
  { name: 'Malaysia',                   type: 'country', lat:   4.21, lon: 101.98 },
  { name: 'Maldives',                   type: 'country', lat:   3.20, lon:  73.22 },
  { name: 'Mongolia',                   type: 'country', lat:  46.86, lon: 103.85 },
  { name: 'Myanmar',                    type: 'country', lat:  19.15, lon:  96.96 },
  { name: 'Nepal',                      type: 'country', lat:  28.39, lon:  84.12 },
  { name: 'North Korea',                type: 'country', lat:  40.34, lon: 127.51 },
  { name: 'Oman',                       type: 'country', lat:  21.47, lon:  55.98 },
  { name: 'Pakistan',                   type: 'country', lat:  30.38, lon:  69.35 },
  { name: 'Palestine',                  type: 'country', lat:  31.95, lon:  35.23 },
  { name: 'Philippines',                type: 'country', lat:  12.88, lon: 121.77 },
  { name: 'Qatar',                      type: 'country', lat:  25.35, lon:  51.18 },
  { name: 'Russia',                     type: 'country', lat:  61.52, lon: 105.32 },
  { name: 'Saudi Arabia',               type: 'country', lat:  23.89, lon:  45.08 },
  { name: 'South Korea',                type: 'country', lat:  35.91, lon: 127.77 },
  { name: 'Sri Lanka',                  type: 'country', lat:   7.87, lon:  80.77 },
  { name: 'Syria',                      type: 'country', lat:  34.80, lon:  38.99 },
  { name: 'Taiwan',                     type: 'country', lat:  23.70, lon: 121.00 },
  { name: 'Tajikistan',                 type: 'country', lat:  38.86, lon:  71.28 },
  { name: 'Thailand',                   type: 'country', lat:  15.87, lon: 100.99 },
  { name: 'Timor-Leste',                type: 'country', lat:  -8.87, lon: 125.73 },
  { name: 'Turkey',                     type: 'country', lat:  38.96, lon:  35.24 },
  { name: 'Turkmenistan',               type: 'country', lat:  38.97, lon:  59.56 },
  { name: 'UAE',                        type: 'country', lat:  23.42, lon:  53.85 },
  { name: 'Uzbekistan',                 type: 'country', lat:  41.38, lon:  64.59 },
  { name: 'Vietnam',                    type: 'country', lat:  14.06, lon: 108.28 },
  { name: 'Yemen',                      type: 'country', lat:  15.55, lon:  48.52 },

  // ── Europe ───────────────────────────────────────────────────────────────
  { name: 'Albania',                    type: 'country', lat:  41.15, lon:  20.17 },
  { name: 'Andorra',                    type: 'country', lat:  42.55, lon:   1.60 },
  { name: 'Austria',                    type: 'country', lat:  47.52, lon:  14.55 },
  { name: 'Belarus',                    type: 'country', lat:  53.71, lon:  27.95 },
  { name: 'Belgium',                    type: 'country', lat:  50.50, lon:   4.47 },
  { name: 'Bosnia and Herzegovina',     type: 'country', lat:  43.92, lon:  17.67 },
  { name: 'Bulgaria',                   type: 'country', lat:  42.73, lon:  25.49 },
  { name: 'Croatia',                    type: 'country', lat:  45.10, lon:  15.20 },
  { name: 'Czech Republic',             type: 'country', lat:  49.82, lon:  15.47 },
  { name: 'Denmark',                    type: 'country', lat:  56.26, lon:   9.50 },
  { name: 'Estonia',                    type: 'country', lat:  58.60, lon:  25.01 },
  { name: 'Finland',                    type: 'country', lat:  61.92, lon:  25.75 },
  { name: 'France',                     type: 'country', lat:  46.23, lon:   2.21 },
  { name: 'Germany',                    type: 'country', lat:  51.17, lon:  10.45 },
  { name: 'Greece',                     type: 'country', lat:  39.07, lon:  21.82 },
  { name: 'Hungary',                    type: 'country', lat:  47.16, lon:  19.50 },
  { name: 'Iceland',                    type: 'country', lat:  64.96, lon: -19.02 },
  { name: 'Ireland',                    type: 'country', lat:  53.41, lon:  -8.24 },
  { name: 'Italy',                      type: 'country', lat:  41.87, lon:  12.57 },
  { name: 'Kosovo',                     type: 'country', lat:  42.60, lon:  20.90 },
  { name: 'Latvia',                     type: 'country', lat:  56.88, lon:  24.60 },
  { name: 'Liechtenstein',              type: 'country', lat:  47.15, lon:   9.55 },
  { name: 'Lithuania',                  type: 'country', lat:  55.17, lon:  23.88 },
  { name: 'Luxembourg',                 type: 'country', lat:  49.82, lon:   6.13 },
  { name: 'Malta',                      type: 'country', lat:  35.94, lon:  14.38 },
  { name: 'Moldova',                    type: 'country', lat:  47.41, lon:  28.37 },
  { name: 'Monaco',                     type: 'country', lat:  43.73, lon:   7.40 },
  { name: 'Montenegro',                 type: 'country', lat:  42.71, lon:  19.37 },
  { name: 'Netherlands',                type: 'country', lat:  52.13, lon:   5.29 },
  { name: 'North Macedonia',            type: 'country', lat:  41.61, lon:  21.75 },
  { name: 'Norway',                     type: 'country', lat:  60.47, lon:   8.47 },
  { name: 'Poland',                     type: 'country', lat:  51.92, lon:  19.15 },
  { name: 'Portugal',                   type: 'country', lat:  39.40, lon:  -8.22 },
  { name: 'Romania',                    type: 'country', lat:  45.94, lon:  24.97 },
  { name: 'San Marino',                 type: 'country', lat:  43.94, lon:  12.46 },
  { name: 'Serbia',                     type: 'country', lat:  44.02, lon:  21.01 },
  { name: 'Slovakia',                   type: 'country', lat:  48.67, lon:  19.70 },
  { name: 'Slovenia',                   type: 'country', lat:  46.15, lon:  14.99 },
  { name: 'Spain',                      type: 'country', lat:  40.46, lon:  -3.75 },
  { name: 'Sweden',                     type: 'country', lat:  60.13, lon:  18.64 },
  { name: 'Switzerland',                type: 'country', lat:  46.82, lon:   8.23 },
  { name: 'Ukraine',                    type: 'country', lat:  48.38, lon:  31.17 },
  { name: 'United Kingdom',             type: 'country', lat:  55.38, lon:  -3.44 },
  { name: 'Vatican City',               type: 'country', lat:  41.90, lon:  12.45 },

  // ── North & Central America + Caribbean ──────────────────────────────────
  { name: 'Antigua and Barbuda',        type: 'country', lat:  17.06, lon: -61.80 },
  { name: 'Bahamas',                    type: 'country', lat:  25.03, lon: -77.40 },
  { name: 'Barbados',                   type: 'country', lat:  13.19, lon: -59.54 },
  { name: 'Belize',                     type: 'country', lat:  17.19, lon: -88.50 },
  { name: 'Canada',                     type: 'country', lat:  56.13, lon:-106.35 },
  { name: 'Costa Rica',                 type: 'country', lat:   9.75, lon: -83.75 },
  { name: 'Cuba',                       type: 'country', lat:  21.52, lon: -79.62 },
  { name: 'Dominica',                   type: 'country', lat:  15.41, lon: -61.37 },
  { name: 'Dominican Republic',         type: 'country', lat:  18.74, lon: -70.16 },
  { name: 'El Salvador',                type: 'country', lat:  13.79, lon: -88.90 },
  { name: 'Grenada',                    type: 'country', lat:  12.26, lon: -61.60 },
  { name: 'Guatemala',                  type: 'country', lat:  15.78, lon: -90.23 },
  { name: 'Haiti',                      type: 'country', lat:  18.97, lon: -72.29 },
  { name: 'Honduras',                   type: 'country', lat:  15.20, lon: -86.24 },
  { name: 'Jamaica',                    type: 'country', lat:  18.11, lon: -77.30 },
  { name: 'Mexico',                     type: 'country', lat:  23.63, lon:-102.55 },
  { name: 'Nicaragua',                  type: 'country', lat:  12.87, lon: -85.21 },
  { name: 'Panama',                     type: 'country', lat:   8.54, lon: -80.78 },
  { name: 'Saint Kitts and Nevis',      type: 'country', lat:  17.36, lon: -62.78 },
  { name: 'Saint Lucia',                type: 'country', lat:  13.91, lon: -60.98 },
  { name: 'Saint Vincent and the Grenadines', type: 'country', lat: 13.25, lon: -61.20 },
  { name: 'Trinidad and Tobago',        type: 'country', lat:  10.69, lon: -61.22 },
  { name: 'United States',              type: 'country', lat:  37.09, lon: -95.71 },

  // ── South America ─────────────────────────────────────────────────────────
  { name: 'Argentina',                  type: 'country', lat: -38.42, lon: -63.62 },
  { name: 'Bolivia',                    type: 'country', lat: -16.29, lon: -63.59 },
  { name: 'Brazil',                     type: 'country', lat: -14.24, lon: -51.93 },
  { name: 'Chile',                      type: 'country', lat: -35.68, lon: -71.54 },
  { name: 'Colombia',                   type: 'country', lat:   4.57, lon: -74.30 },
  { name: 'Ecuador',                    type: 'country', lat:  -1.83, lon: -78.18 },
  { name: 'Guyana',                     type: 'country', lat:   4.86, lon: -58.93 },
  { name: 'Paraguay',                   type: 'country', lat: -23.44, lon: -58.44 },
  { name: 'Peru',                       type: 'country', lat:  -9.19, lon: -75.02 },
  { name: 'Suriname',                   type: 'country', lat:   3.92, lon: -56.03 },
  { name: 'Uruguay',                    type: 'country', lat: -32.52, lon: -55.77 },
  { name: 'Venezuela',                  type: 'country', lat:   6.42, lon: -66.59 },

  // ── Oceania ───────────────────────────────────────────────────────────────
  { name: 'Australia',                  type: 'country', lat: -25.27, lon: 133.78 },
  { name: 'Fiji',                       type: 'country', lat: -17.71, lon: 178.06 },
  { name: 'Kiribati',                   type: 'country', lat:   1.87, lon:-157.36 },
  { name: 'Marshall Islands',           type: 'country', lat:   7.13, lon: 171.18 },
  { name: 'Micronesia',                 type: 'country', lat:   7.43, lon: 150.55 },
  { name: 'Nauru',                      type: 'country', lat:  -0.52, lon: 166.93 },
  { name: 'New Zealand',                type: 'country', lat: -40.90, lon: 174.89 },
  { name: 'Palau',                      type: 'country', lat:   7.51, lon: 134.58 },
  { name: 'Papua New Guinea',           type: 'country', lat:  -6.31, lon: 143.96 },
  { name: 'Samoa',                      type: 'country', lat: -13.76, lon:-172.10 },
  { name: 'Solomon Islands',            type: 'country', lat:  -9.64, lon: 160.16 },
  { name: 'Tonga',                      type: 'country', lat: -21.18, lon:-175.20 },
  { name: 'Tuvalu',                     type: 'country', lat:  -7.11, lon: 177.65 },
  { name: 'Vanuatu',                    type: 'country', lat: -15.38, lon: 166.96 },

  // ── Oceans & Seas ─────────────────────────────────────────────────────────
  { name: 'Pacific Ocean',              type: 'ocean', lat:   0.0, lon: -160.0 },
  { name: 'Atlantic Ocean',             type: 'ocean', lat:   0.0, lon:  -30.0 },
  { name: 'Indian Ocean',               type: 'ocean', lat: -20.0, lon:   80.0 },
  { name: 'Arctic Ocean',               type: 'ocean', lat:  82.0, lon:    0.0 },
  { name: 'Southern Ocean',             type: 'ocean', lat: -60.0, lon:    0.0 },
  { name: 'Mediterranean Sea',          type: 'ocean', lat:  35.0, lon:   18.0 },
  { name: 'Caribbean Sea',              type: 'ocean', lat:  15.0, lon:  -75.0 },

  // ── Lakes ────────────────────────────────────────────────────────────────
  { name: 'Caspian Sea',                type: 'lake', lat:  41.40, lon:   51.50 },
  { name: 'Lake Superior',              type: 'lake', lat:  47.72, lon:  -87.50 },
  { name: 'Lake Victoria',              type: 'lake', lat:  -1.00, lon:   33.00 },
  { name: 'Lake Baikal',                type: 'lake', lat:  53.50, lon:  108.00 },
  { name: 'Great Bear Lake',            type: 'lake', lat:  65.95, lon: -121.05 },
  { name: 'Lake Tanganyika',            type: 'lake', lat:  -6.50, lon:   29.60 },
  { name: 'Lake Titicaca',              type: 'lake', lat: -15.80, lon:  -69.40 },
  { name: 'Lake Ladoga',                type: 'lake', lat:  60.82, lon:   31.50 },
  { name: 'Lake Malawi',                type: 'lake', lat: -12.18, lon:   34.37 },
  { name: 'Great Salt Lake',            type: 'lake', lat:  41.17, lon: -112.58 },

  // ── Mountain ranges ──────────────────────────────────────────────────────
  { name: 'Himalayas',                  type: 'mountainRange', lat:  28.00, lon:   86.00 },
  { name: 'Alps',                       type: 'mountainRange', lat:  46.50, lon:   10.00 },
  { name: 'Andes',                      type: 'mountainRange', lat: -20.00, lon:  -70.00 },
  { name: 'Rocky Mountains',            type: 'mountainRange', lat:  43.00, lon: -110.00 },
  { name: 'Atlas Mountains',            type: 'mountainRange', lat:  31.00, lon:   -7.50 },
  { name: 'Ural Mountains',             type: 'mountainRange', lat:  60.00, lon:   60.00 },
  { name: 'Caucasus Mountains',         type: 'mountainRange', lat:  42.50, lon:   44.00 },
  { name: 'Carpathian Mountains',       type: 'mountainRange', lat:  47.00, lon:   25.00 },
  { name: 'Great Dividing Range',       type: 'mountainRange', lat: -25.00, lon:  150.00 },
  { name: 'Southern Alps',              type: 'mountainRange', lat: -43.50, lon:  170.50 },

  // ── Peninsulas ───────────────────────────────────────────────────────────
  { name: 'Arabian Peninsula',          type: 'peninsula', lat:  23.50, lon:   45.00 },
  { name: 'Iberian Peninsula',          type: 'peninsula', lat:  40.30, lon:   -4.00 },
  { name: 'Scandinavian Peninsula',     type: 'peninsula', lat:  62.00, lon:   15.00 },
  { name: 'Balkan Peninsula',           type: 'peninsula', lat:  42.00, lon:   22.00 },
  { name: 'Italian Peninsula',          type: 'peninsula', lat:  42.50, lon:   12.50 },
  { name: 'Korean Peninsula',           type: 'peninsula', lat:  38.30, lon:  127.50 },
  { name: 'Malay Peninsula',            type: 'peninsula', lat:   7.00, lon:  100.00 },
  { name: 'Yucatan Peninsula',          type: 'peninsula', lat:  19.50, lon:  -89.00 },
  { name: 'Kamchatka Peninsula',        type: 'peninsula', lat:  57.00, lon:  160.00 },
  { name: 'Florida Peninsula',          type: 'peninsula', lat:  28.30, lon:  -81.60 },

  // ── Deserts ──────────────────────────────────────────────────────────────
  { name: 'Sahara Desert',              type: 'desert', lat:  23.50, lon:   13.00 },
  { name: 'Arabian Desert',             type: 'desert', lat:  22.00, lon:   45.00 },
  { name: 'Gobi Desert',                type: 'desert', lat:  42.50, lon:  103.00 },
  { name: 'Kalahari Desert',            type: 'desert', lat: -23.00, lon:   22.00 },
  { name: 'Atacama Desert',             type: 'desert', lat: -24.50, lon:  -69.25 },
  { name: 'Mojave Desert',              type: 'desert', lat:  35.00, lon: -115.00 },
  { name: 'Great Victoria Desert',      type: 'desert', lat: -29.00, lon:  129.00 },
  { name: 'Thar Desert',                type: 'desert', lat:  27.00, lon:   71.00 },
  { name: 'Namib Desert',               type: 'desert', lat: -24.75, lon:   15.30 },
  { name: 'Patagonian Desert',          type: 'desert', lat: -44.00, lon:  -69.00 },

  // ── Cities ────────────────────────────────────────────────────────────────
  { name: 'New York',    type: 'city', lat:  40.71, lon:  -74.01 },
  { name: 'Tokyo',       type: 'city', lat:  35.68, lon:  139.69 },
  { name: 'London',      type: 'city', lat:  51.51, lon:   -0.13 },
  { name: 'Paris',       type: 'city', lat:  48.85, lon:    2.35 },
  { name: 'Dubai',       type: 'city', lat:  25.20, lon:   55.27 },
  { name: 'Singapore',   type: 'city', lat:   1.35, lon:  103.82 },
  { name: 'Sao Paulo',   type: 'city', lat: -23.55, lon:  -46.63 },
  { name: 'Cape Town',   type: 'city', lat: -33.92, lon:   18.42 },
  { name: 'Istanbul',    type: 'city', lat:  41.01, lon:   28.95 },
  { name: 'Mumbai',      type: 'city', lat:  19.08, lon:   72.88 },
  { name: 'Cairo',       type: 'city', lat:  30.06, lon:   31.24 },
  { name: 'Sydney',      type: 'city', lat: -33.87, lon:  151.21 },
  { name: 'Los Angeles', type: 'city', lat:  34.05, lon: -118.24 },
  { name: 'Moscow',      type: 'city', lat:  55.75, lon:   37.62 },
  { name: 'Beijing',     type: 'city', lat:  39.91, lon:  116.39 },
  { name: 'Mexico City', type: 'city', lat:  19.43, lon:  -99.13 },
  { name: 'Lagos',       type: 'city', lat:   6.52, lon:    3.38 },
  { name: 'Buenos Aires',type: 'city', lat: -34.61, lon:  -58.38 },
  { name: 'Bangkok',     type: 'city', lat:  13.75, lon:  100.52 },
];

const FI_NAMES = {
  Algeria: 'Algeria',
  Angola: 'Angola',
  Benin: 'Benin',
  Botswana: 'Botswana',
  'Burkina Faso': 'Burkina Faso',
  Burundi: 'Burundi',
  'Cabo Verde': 'Kap Verde',
  Cameroon: 'Kamerun',
  'Central African Republic': 'Keski-Afrikan tasavalta',
  Chad: 'Tšad',
  Comoros: 'Komorit',
  Congo: 'Kongo',
  'DR Congo': 'Kongon demokraattinen tasavalta',
  Djibouti: 'Djibouti',
  Egypt: 'Egypti',
  'Equatorial Guinea': 'Päiväntasaajan Guinea',
  Eritrea: 'Eritrea',
  Eswatini: 'Eswatini',
  Ethiopia: 'Etiopia',
  Gabon: 'Gabon',
  Gambia: 'Gambia',
  Ghana: 'Ghana',
  Guinea: 'Guinea',
  'Guinea-Bissau': 'Guinea-Bissau',
  'Ivory Coast': 'Norsunluurannikko',
  Kenya: 'Kenia',
  Lesotho: 'Lesotho',
  Liberia: 'Liberia',
  Libya: 'Libya',
  Madagascar: 'Madagaskar',
  Malawi: 'Malawi',
  Mali: 'Mali',
  Mauritania: 'Mauritania',
  Mauritius: 'Mauritius',
  Morocco: 'Marokko',
  Mozambique: 'Mosambik',
  Namibia: 'Namibia',
  Niger: 'Niger',
  Nigeria: 'Nigeria',
  Rwanda: 'Ruanda',
  'São Tomé and Príncipe': 'São Tomé ja Príncipe',
  Senegal: 'Senegal',
  Seychelles: 'Seychellit',
  'Sierra Leone': 'Sierra Leone',
  Somalia: 'Somalia',
  'South Africa': 'Etelä-Afrikka',
  'South Sudan': 'Etelä-Sudan',
  Sudan: 'Sudan',
  Tanzania: 'Tansania',
  Togo: 'Togo',
  Tunisia: 'Tunisia',
  Uganda: 'Uganda',
  Zambia: 'Sambia',
  Zimbabwe: 'Zimbabwe',
  Afghanistan: 'Afganistan',
  Armenia: 'Armenia',
  Azerbaijan: 'Azerbaidžan',
  Bahrain: 'Bahrain',
  Bangladesh: 'Bangladesh',
  Bhutan: 'Bhutan',
  Brunei: 'Brunei',
  Cambodia: 'Kambodža',
  China: 'Kiina',
  Cyprus: 'Kypros',
  Georgia: 'Georgia',
  India: 'Intia',
  Indonesia: 'Indonesia',
  Iran: 'Iran',
  Iraq: 'Irak',
  Israel: 'Israel',
  Japan: 'Japani',
  Jordan: 'Jordania',
  Kazakhstan: 'Kazakstan',
  Kuwait: 'Kuwait',
  Kyrgyzstan: 'Kirgisia',
  Laos: 'Laos',
  Lebanon: 'Libanon',
  Malaysia: 'Malesia',
  Maldives: 'Malediivit',
  Mongolia: 'Mongolia',
  Myanmar: 'Myanmar',
  Nepal: 'Nepal',
  'North Korea': 'Pohjois-Korea',
  Oman: 'Oman',
  Pakistan: 'Pakistan',
  Palestine: 'Palestiina',
  Philippines: 'Filippiinit',
  Qatar: 'Qatar',
  Russia: 'Venäjä',
  'Saudi Arabia': 'Saudi-Arabia',
  'South Korea': 'Etelä-Korea',
  'Sri Lanka': 'Sri Lanka',
  Syria: 'Syyria',
  Taiwan: 'Taiwan',
  Tajikistan: 'Tadžikistan',
  Thailand: 'Thaimaa',
  'Timor-Leste': 'Itä-Timor',
  Turkey: 'Turkki',
  Turkmenistan: 'Turkmenistan',
  UAE: 'Arabiemiirikunnat',
  Uzbekistan: 'Uzbekistan',
  Vietnam: 'Vietnam',
  Yemen: 'Jemen',
  Albania: 'Albania',
  Andorra: 'Andorra',
  Austria: 'Itävalta',
  Belarus: 'Valko-Venäjä',
  Belgium: 'Belgia',
  'Bosnia and Herzegovina': 'Bosnia ja Hertsegovina',
  Bulgaria: 'Bulgaria',
  Croatia: 'Kroatia',
  'Czech Republic': 'Tshekki',
  Denmark: 'Tanska',
  Estonia: 'Viro',
  Finland: 'Suomi',
  France: 'Ranska',
  Germany: 'Saksa',
  Greece: 'Kreikka',
  Hungary: 'Unkari',
  Iceland: 'Islanti',
  Ireland: 'Irlanti',
  Italy: 'Italia',
  Kosovo: 'Kosovo',
  Latvia: 'Latvia',
  Liechtenstein: 'Liechtenstein',
  Lithuania: 'Liettua',
  Luxembourg: 'Luxemburg',
  Malta: 'Malta',
  Moldova: 'Moldova',
  Monaco: 'Monaco',
  Montenegro: 'Montenegro',
  Netherlands: 'Alankomaat',
  'North Macedonia': 'Pohjois-Makedonia',
  Norway: 'Norja',
  Poland: 'Puola',
  Portugal: 'Portugali',
  Romania: 'Romania',
  'San Marino': 'San Marino',
  Serbia: 'Serbia',
  Slovakia: 'Slovakia',
  Slovenia: 'Slovenia',
  Spain: 'Espanja',
  Sweden: 'Ruotsi',
  Switzerland: 'Sveitsi',
  Ukraine: 'Ukraina',
  'United Kingdom': 'Yhdistynyt kuningaskunta',
  'Vatican City': 'Vatikaani',
  'Antigua and Barbuda': 'Antigua ja Barbuda',
  Bahamas: 'Bahama',
  Barbados: 'Barbados',
  Belize: 'Belize',
  Canada: 'Kanada',
  'Costa Rica': 'Costa Rica',
  Cuba: 'Kuuba',
  Dominica: 'Dominica',
  'Dominican Republic': 'Dominikaaninen tasavalta',
  'El Salvador': 'El Salvador',
  Grenada: 'Grenada',
  Guatemala: 'Guatemala',
  Haiti: 'Haiti',
  Honduras: 'Honduras',
  Jamaica: 'Jamaika',
  Mexico: 'Meksiko',
  Nicaragua: 'Nicaragua',
  Panama: 'Panama',
  'Saint Kitts and Nevis': 'Saint Kitts ja Nevis',
  'Saint Lucia': 'Saint Lucia',
  'Saint Vincent and the Grenadines': 'Saint Vincent ja Grenadiinit',
  'Trinidad and Tobago': 'Trinidad ja Tobago',
  'United States': 'Yhdysvallat',
  Argentina: 'Argentiina',
  Bolivia: 'Bolivia',
  Brazil: 'Brasilia',
  Chile: 'Chile',
  Colombia: 'Kolumbia',
  Ecuador: 'Ecuador',
  Guyana: 'Guyana',
  Paraguay: 'Paraguay',
  Peru: 'Peru',
  Suriname: 'Suriname',
  Uruguay: 'Uruguay',
  Venezuela: 'Venezuela',
  Australia: 'Australia',
  Fiji: 'Fidzi',
  Kiribati: 'Kiribati',
  'Marshall Islands': 'Marshallinsaaret',
  Micronesia: 'Mikronesia',
  Nauru: 'Nauru',
  'New Zealand': 'Uusi-Seelanti',
  Palau: 'Palau',
  'Papua New Guinea': 'Papua-Uusi-Guinea',
  Samoa: 'Samoa',
  'Solomon Islands': 'Salomonsaaret',
  Tonga: 'Tonga',
  Tuvalu: 'Tuvalu',
  Vanuatu: 'Vanuatu',
  'Pacific Ocean': 'Tyynimeri',
  'Atlantic Ocean': 'Atlantin valtameri',
  'Indian Ocean': 'Intian valtameri',
  'Arctic Ocean': 'Pohjoinen jäämeri',
  'Southern Ocean': 'Eteläinen jäämeri',
  'Mediterranean Sea': 'Välimeri',
  'Caribbean Sea': 'Karibianmeri',
  'Caspian Sea': 'Kaspianmeri',
  'Lake Superior': 'Yläjärvi',
  'Lake Victoria': 'Victoriajärvi',
  'Lake Baikal': 'Baikaljärvi',
  'Great Bear Lake': 'Iso Karhujärvi',
  'Lake Tanganyika': 'Tanganjikajärvi',
  'Lake Titicaca': 'Titicacajärvi',
  'Lake Ladoga': 'Laatokka',
  'Lake Malawi': 'Malawijärvi',
  'Great Salt Lake': 'Iso Suolajärvi',
  Himalayas: 'Himalaja',
  Alps: 'Alpit',
  Andes: 'Andit',
  'Rocky Mountains': 'Kalliovuoret',
  'Atlas Mountains': 'Atlasvuoret',
  'Ural Mountains': 'Uralvuoret',
  'Caucasus Mountains': 'Kaukasusvuoret',
  'Carpathian Mountains': 'Karpaatit',
  'Great Dividing Range': 'Iso vedenjakajavuoristo',
  'Southern Alps': 'Etelaiset Alpit',
  'Arabian Peninsula': 'Arabian niemimaa',
  'Iberian Peninsula': 'Iberian niemimaa',
  'Scandinavian Peninsula': 'Skandinavian niemimaa',
  'Balkan Peninsula': 'Balkanin niemimaa',
  'Italian Peninsula': 'Italian niemimaa',
  'Korean Peninsula': 'Korean niemimaa',
  'Malay Peninsula': 'Malakan niemimaa',
  'Yucatan Peninsula': 'Jukatanin niemimaa',
  'Kamchatka Peninsula': 'Kamtšatkan niemimaa',
  'Florida Peninsula': 'Floridan niemimaa',
  'Sahara Desert': 'Sahara',
  'Arabian Desert': 'Arabian aavikko',
  'Gobi Desert': 'Gobin aavikko',
  'Kalahari Desert': 'Kalahari',
  'Atacama Desert': 'Atacaman aavikko',
  'Mojave Desert': 'Mojaven aavikko',
  'Great Victoria Desert': 'Iso Victorian aavikko',
  'Thar Desert': 'Tharin aavikko',
  'Namib Desert': 'Namibin aavikko',
  'Patagonian Desert': 'Patagonian aavikko',
  'New York': 'New York',
  Tokyo: 'Tokio',
  London: 'Lontoo',
  Paris: 'Pariisi',
  Dubai: 'Dubai',
  Singapore: 'Singapore',
  'Sao Paulo': 'São Paulo',
  'Cape Town': 'Kapkaupunki',
  Istanbul: 'Istanbul',
  Mumbai: 'Mumbai',
  Cairo: 'Kairo',
  Sydney: 'Sydney',
  'Los Angeles': 'Los Angeles',
  Moscow: 'Moskova',
  Beijing: 'Peking',
  'Mexico City': 'México',
  Lagos: 'Lagos',
  'Buenos Aires': 'Buenos Aires',
  Bangkok: 'Bangkok',
};

export const PLACES = RAW_PLACES.map((place) => ({
  ...place,
  nameFi: FI_NAMES[place.name] ?? place.name,
}));
